name: chiw_express
description: A food delivery app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.0.0
  google_fonts: ^6.0.0
  flutter_spinkit: ^5.1.0
  geocoding: ^3.0.0
  flutter_stripe: ^11.0.0
  google_sign_in: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true